### ISSUE TITLE
Issue accessing hyper-db

### ISSUE THREAD

**Issue by kpruss** [montilab/hypeR-db#1]
Hi, I just downloaded hypeR and am having trouble accessing hyperdb. 

I can successfully download from msigdb using hypeR with `msigdb_download_one(species="Homo sapiens", category="H")` as in the tutorial.

`hyperdb_info(type = "gsets", quiet = FALSE)` results in:
Getting available gsets ... 
 Show Traceback
Error in gh_process_response(raw) : GitHub API error (404): 404 Not Found Message: Not Found Read more at https://developer.github.com/v3/repos/contents/#get-contents URL not found: https://api.github.com/repos/montilab/hyperdb/contents/data/gsets

and `gsets <- hyperdb_fetch(type="gsets", "KEGG_2019_Human")` results in:
Error in readRDS(temp) : unknown input format.

Thanks much!

**Edit, accessing enrichR also seems to not be working

Attempting 

`ATLAS <- enrichr_gsets("Human_Gene_Atlas")`
`available <- enrichr_available() # not working`
`reactable(available)`

results in:
Error in enrichr_gsets("Human_Gene_Atlas") : 
  could not find function "enrichr_gsets"
Error in enrichr_available() : 
  could not find function "enrichr_available"
Error in reactable(available) : could not find function "reactable"

I'm working with bacterial genomes and so ultimately want to be able to work with/download KEGG and BioCyc pathways for different bacterial species.

The function posted on your hypeR-db page
`get.rgsets <- function(rgsets) {
    url <- "https://github.com/montilab/hyperdb/raw/master/data/{0}.rds"
    temp <- tempfile(fileext=".rds")
    httr::GET(gsub("\\{0}", rgsets, url), 
              .send_headers = c("Accept" = "application/octet-stream"),
              httr::write_disk(temp, overwrite=TRUE))    
    return(readRDS(temp))
}`
works well, is there a way to modify the input `rgsets <- get.rgsets("KEGG/KEGG_v92.0")` for e.g. different species within KEGG?

**Comment by anfederico** [comment]
Closed this. We're currently changing the structure of the repository and some of the syntax has changed. If you still have difficulties, please open a new issue.
